# 🐼 Pandas Mastery Challenge Workbook
### 100 Comprehensive Practice Questions (Beginner to Pro)
**Dataset context:** `netflix_titles.csv`

Use this notebook to solve the challenge questions. For each question, an empty code cell has been provided below the prompt for your implementation.

## Phase 1: Beginner Level Foundations (Q1 - Q25)

#### **Q1.** How do you import the pandas library and read the netflix_titles.csv dataset into a DataFrame named 'df'?

In [2]:
import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

#### **Q2.** How do you display the first 5 rows and the last 5 rows of the Netflix DataFrame?

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

#### **Q3.** How can you find the total number of rows and columns in this dataset?

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

#### **Q4.** Write a command to output all the column names of the DataFrame.

In [5]:
display(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

#### **Q5.** How do you inspect the data types of each column alongside non-null counts using a built-in pandas method?

In [6]:
df.columns.dtype
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

#### **Q6.** How can you obtain a summary of basic statistics (mean, min, max, count) for the numeric columns?

In [7]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

#### **Q7.** How do you count the exact number of missing values (NaN) in every single column?

In [8]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

#### **Q8.** Select only the 'title' column from the DataFrame. What are the two different syntaxes to achieve this?

In [9]:
df.title
df['title'].head()

0     Dick Johnson Is Dead
1            Blood & Water
2                Ganglands
3    Jailbirds New Orleans
4             Kota Factory
Name: title, dtype: str

#### **Q9.** Extract a new DataFrame that contains only three specific columns: 'title', 'type', and 'release_year'.

In [10]:
df[['title','type','release_year']]

                      title     type  release_year
0      Dick Johnson Is Dead    Movie          2020
1             Blood & Water  TV Show          2021
2                 Ganglands  TV Show          2021
3     Jailbirds New Orleans  TV Show          2021
4              Kota Factory  TV Show          2021
...                     ...      ...           ...
8802                 Zodiac    Movie          2007
8803            Zombie Dumb  TV Show          2018
8804             Zombieland    Movie          2009
8805                   Zoom    Movie          2006
8806                 Zubaan    Movie          2015

[8807 rows x 3 columns]

#### **Q10.** How do you filter the DataFrame to show only rows where the 'type' is equal to 'Movie'?

In [11]:
df.loc[df['type']=='Movie']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### **Q11.** How do you filter the rows to show only 'TV Show' entries?

In [12]:
df.loc[df['type']=='TV Show']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

#### **Q12.** Find the total count of unique values in the 'type' column to see how many distinct categories exist.

In [13]:
df['type'].nunique()
df.type.unique

<bound method Series.unique of 0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: str>

#### **Q13.** List all unique values present in the 'rating' column.

In [14]:
list(df.rating.unique())
df.rating.unique().tolist()

['PG-13',
 'TV-MA',
 'PG',
 'TV-14',
 'TV-PG',
 'TV-Y',
 'TV-Y7',
 'R',
 'TV-G',
 'G',
 'NC-17',
 '74 min',
 '84 min',
 '66 min',
 'NR',
 nan,
 'TV-Y7-FV',
 'UR']

#### **Q14.** How do you count how many times each unique 'rating' appears in the dataset?

In [15]:
df.rating.value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

#### **Q15.** Find the frequency count of each unique value in the 'release_year' column.

In [16]:
df['release_year'].value_counts()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1959       1
1925       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

#### **Q16.** How do you select the row at index position 10 using integer-based indexing (.iloc)?

In [17]:
df.iloc[10]

show_id                                                       s11
type                                                      TV Show
title                         Vendetta: Truth, Lies and The Mafia
director                                                      NaN
cast                                                          NaN
country                                                       NaN
date_added                                     September 24, 2021
release_year                                                 2021
rating                                                      TV-MA
duration                                                 1 Season
listed_in       Crime TV Shows, Docuseries, International TV S...
description     Sicily boasts a bold "Anti-Mafia" coalition. B...
Name: 10, dtype: object

#### **Q17.** How do you select rows from index 10 to 20 (inclusive) and columns from 'show_id' to 'director' using label-based indexing (.loc)?

In [18]:
df.loc[10:20,'show_id':'director']

,show_id,type,title,director
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri
12,s13,Movie,Je Suis Karl,Christian Schwochow
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti
14,s15,TV Show,Crime Stories: India Detectives,NaN
15,s16,TV Show,Dear White People,NaN
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams"
17,s18,TV Show,Falsa identidad,NaN
18,s19,Movie,Intrusion,Adam Salky
19,s20,TV Show,Jaguar,NaN
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton

#### **Q18.** How can you check if the 'show_id' column contains any duplicate values?

In [19]:
df.show_id.duplicated().sum()

np.int64(0)

#### **Q19.** Rename the column 'listed_in' to 'genre' and 'cast' to 'actors' in place.

In [20]:
df.rename(columns={'listed_in': 'genre', 'cast': 'actors'})

,show_id,type,title,director,actors,country,date_added,release_year,rating,duration,genre,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### **Q20.** Sort the entire DataFrame by the 'release_year' column in ascending order.

In [21]:
df.sort_values(by='release_year',ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
781,s782,Movie,Black Holes | The Edge of All We Know,Peter Galison,NaN,NaN,"June 2, 2021",2021,TV-14,99 min,Documentaries,Follow scientists on their quest to understand...
762,s763,Movie,Sweet & Sour,Lee Kae-byeok,"Jang Ki-yong, Chae Soo-bin, Jung Soo-jung",South Korea,"June 4, 2021",2021,TV-14,103 min,"Comedies, International Movies, Romantic Movies",Faced with real-world opportunities and challe...
763,s764,TV Show,Sweet Tooth,NaN,"Nonso Anozie, Christian Convery, Adeel Akhtar,...",United States,"June 4, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",On a perilous adventure across a post-apocalyp...
764,s765,Movie,Trippin' with the Kandasamys,Jayan Moodley,"Jailoshini Naidoo, Maeshni Naicker, Madhushan ...",South Africa,"June 4, 2021",2021,TV-14,94 min,"Comedies, International Movies, Romantic Movies","To rekindle their marriages, best friends-turn..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

#### **Q21.** Sort the DataFrame by 'release_year' in descending order so that the newest releases appear first.

In [22]:
df.sort_values(by='release_year', ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
781,s782,Movie,Black Holes | The Edge of All We Know,Peter Galison,NaN,NaN,"June 2, 2021",2021,TV-14,99 min,Documentaries,Follow scientists on their quest to understand...
762,s763,Movie,Sweet & Sour,Lee Kae-byeok,"Jang Ki-yong, Chae Soo-bin, Jung Soo-jung",South Korea,"June 4, 2021",2021,TV-14,103 min,"Comedies, International Movies, Romantic Movies",Faced with real-world opportunities and challe...
763,s764,TV Show,Sweet Tooth,NaN,"Nonso Anozie, Christian Convery, Adeel Akhtar,...",United States,"June 4, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",On a perilous adventure across a post-apocalyp...
764,s765,Movie,Trippin' with the Kandasamys,Jayan Moodley,"Jailoshini Naidoo, Maeshni Naicker, Madhushan ...",South Africa,"June 4, 2021",2021,TV-14,94 min,"Comedies, International Movies, Romantic Movies","To rekindle their marriages, best friends-turn..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

#### **Q22.** How do you reset the index of a DataFrame after sorting it, ensuring the old index is completely dropped?

In [23]:
new_df = df.sort_values(by='release_year').reset_index()
new_df

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
1,7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
2,8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
3,8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
4,8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,862,s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...
8803,861,s862,Movie,Little Singham Future mein Satakli,Prakash Satam,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"May 20, 2021",2021,TV-Y7,47 min,"Children & Family Movies, Comedies",Little Singham and his crew travel to the year...
8804,857,s858,TV Show,The Neighbor,NaN,"Quim Gutiérrez, Clara Lago, Adrián Pino, Catel...",Spain,"May 21, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",Self-centered Javier's life gets a bit messy w...
8805,876,s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
8806,965,s966,TV Show,Yasuke,NaN,"LaKeith Stanfield, Takehiro Hira, Maya Tanida,...",NaN,"April 29, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows",A peaceful boatman once known as the Black Sam...

#### **Q23.** Drop the 'description' column entirely from the DataFrame and return a new DataFrame.

In [24]:
df1 = df.drop(columns='title')
df1

,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### **Q24.** How do you drop both 'director' and 'cast' columns simultaneously within a single line of code?

In [25]:
df2 = df.drop(columns=['director','cast'])

#### **Q25.** Create a new column named 'dataset_source' where every single row contains the static string value 'Netflix'.

In [26]:
df['dataset_source']='Netfilx'
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Netfilx
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Netfilx
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netfilx
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netfilx
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netfilx
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx

## Phase 2: Intermediate Data Wrangling & Analysis (Q26 - Q60)

#### **Q26.** Filter the dataset to find all rows where 'type' is 'Movie' AND the 'release_year' is exactly 2021.

In [27]:
df.loc[(df['type']=='Movie') & (df['release_year']==2021)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Netfilx
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,Netfilx
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,Netfilx
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...,Netfilx
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...,Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,s1426,Movie,Creating The Queen's Gambit,NaN,NaN,United States,"January 8, 2021",2021,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...,Netfilx
1431,s1432,Movie,Stuck Apart,NaN,"Engin Günaydın, Haluk Bilginer, Binnur Kaya, Ö...",Turkey,"January 8, 2021",2021,TV-MA,97 min,"Comedies, Dramas, International Movies","Entrenched in a midlife crisis, Aziz seeks sol...",Netfilx
1436,s1437,Movie,Ratones Paranoicos: The Band that Rocked Argen...,"Alejandro Ruax, Ramiro Martínez","Juan Sebastián Gutiérrez, Pablo Cano, Pablo Me...",NaN,"January 6, 2021",2021,TV-MA,76 min,"Documentaries, International Movies, Music & M...","The irrepressible Ratones Paranoicos, Argentin...",Netfilx
1466,s1467,Movie,The Minimalists: Less Is Now,NaN,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,Netfilx
1468,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a...",Netfilx

#### **Q27.** Filter the dataset for rows where 'country' is either 'United States' OR 'India'.

In [28]:
df.loc[df['country'].isin(['United States','India'])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Netfilx
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,Netfilx
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...,Netfilx
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...,Netfilx
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netfilx
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netfilx
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx

#### **Q28.** How do you select rows where the 'country' column value is missing (NaN)?

In [29]:
df.loc[df['country'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Netfilx
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Netfilx
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,Netfilx
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Netfilx
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B...",Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8718,s8719,Movie,Westside vs. the World,Michael Fahey,"Ron Perlman, Louie Simmons",NaN,"August 9, 2019",2019,TV-MA,96 min,"Documentaries, Sports Movies",A look into the journey of influential strengt...,Netfilx
8759,s8760,Movie,World's Weirdest Homes,Storm Theunissen,Charlie Luxton,NaN,"February 1, 2019",2015,TV-PG,49 min,Movies,From a bubble-shaped palace to an island built...,Netfilx
8783,s8784,TV Show,Yoko,NaN,"Eileen Stevens, Alyson Leigh Rosenfeld, Sarah ...",NaN,"June 23, 2018",2016,TV-Y,1 Season,Kids' TV,"Friends Mai, Oto and Vik's games at the park b...",Netfilx
8785,s8786,TV Show,YOM,NaN,"Sairaj, Devyani Dagaonkar, Ketan Singh, Mayur ...",NaN,"June 7, 2018",2016,TV-Y7,1 Season,Kids' TV,"With the mind of a human being, and the body o...",Netfilx
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netfilx

#### **Q29.** How do you find all rows where the 'director' column is NOT missing (is valid)?

In [30]:
df.loc[df['director'].notna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Netfilx
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,Netfilx
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Netfilx
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,Netfilx
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netfilx
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netfilx
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx

#### **Q30.** Use the .isin() method to filter the DataFrame for rows where the 'rating' is 'PG', 'PG-13', or 'R'.

In [31]:
df.loc[df['rating'].isin(['PG','PG-13','R'])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Netfilx
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,Netfilx
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...,Netfilx
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...,Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8791,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...,Netfilx
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,88 min,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...,Netfilx
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netfilx
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netfilx

#### **Q31.** Find all records where the 'release_year' falls strictly between 2018 and 2020 inclusive using a single boundary method.

In [32]:
df.loc[(df['release_year']>2018) & (df['release_year']<=2020)]
df.loc[df['release_year'].between(2018, 2020)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...,Netfilx
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...,Netfilx
21,s22,TV Show,Resurrection: Ertugrul,NaN,"Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar...",Turkey,"September 22, 2021",2018,TV-14,5 Seasons,"International TV Shows, TV Action & Adventure,...",When a good deed unwittingly endangers his cla...,Netfilx
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...,Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8752,s8753,Movie,Wish Man,Theo Davies,"Andrew Steel, Kirby Bliss Blanton, Tom Sizemor...",United States,"December 3, 2019",2019,TV-14,108 min,"Children & Family Movies, Dramas","After surviving a life-threatening accident, a...",Netfilx
8756,s8757,Movie,Woodstock,Barak Goodman,NaN,United States,"August 13, 2019",2019,TV-MA,97 min,"Documentaries, Music & Musicals",For the 50th anniversary of the legendary Wood...,Netfilx
8774,s8775,Movie,يوم الدين,Abu Bakr Shawky,"Rady Gamal, Ahmed Abdelhafiz, Shahira Fahmy, S...","Egypt, Austria, United States","October 22, 2019",2018,TV-14,97 min,"Dramas, Independent Movies, International Movies",A man cured of leprosy and a young orphan leav...,Netfilx
8775,s8776,TV Show,Yeh Meri Family,NaN,"Vishesh Bansal, Mona Singh, Akarsh Khurana, Ah...",India,"August 31, 2018",2018,TV-PG,1 Season,"International TV Shows, TV Comedies","In the summer of 1998, middle child Harshu bal...",Netfilx
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netfilx

#### **Q32.** How do you calculate the mean, median, minimum, and maximum values of the 'release_year' column?

In [33]:
df['release_year'].mean()
df['release_year'].median()
df['release_year'].max()
df['release_year'].min()

np.int64(1925)

#### **Q33.** Group the DataFrame by the 'type' column and calculate the total count of titles within each group.

In [34]:
df.groupby('type')['title'].value_counts()

type     title
Movie    Dick Johnson Is Dead        1
         Under the Shadow            1
         Jim Gaffigan: Cinco         1
         Very Big Shot               1
         Clinical                    1
                                    ..
TV Show  Lenox Hill                  1
         Someone Like You            1
         DC's Legends of Tomorrow    1
         Love Family                 1
         Medal of Honor              1
Name: count, Length: 8807, dtype: int64

#### **Q34.** Group by 'rating' and find the average/mean 'release_year' for each rating category.

In [35]:
df.groupby('rating')['release_year'].mean()

rating
66 min      2015.000000
74 min      2017.000000
84 min      2010.000000
G           1997.804878
NC-17       2015.000000
NR          2010.912500
PG          2008.428571
PG-13       2009.314286
R           2010.471840
TV-14       2013.655556
TV-G        2015.745455
TV-MA       2016.661678
TV-PG       2013.529548
TV-Y        2017.159609
TV-Y7       2015.508982
TV-Y7-FV    2014.833333
UR          1999.333333
Name: release_year, dtype: float64

#### **Q35.** Group the data by both 'type' and 'rating' simultaneously and count the number of rows for each combination.

In [36]:
df.groupby(['type', 'rating']).size()

type     rating
Movie    66 min         1
         74 min         1
         84 min         1
         G             41
         NC-17          3
         NR            75
         PG           287
         PG-13        490
         R            797
         TV-14       1427
         TV-G         126
         TV-MA       2062
         TV-PG        540
         TV-Y         131
         TV-Y7        139
         TV-Y7-FV       5
         UR             3
TV Show  NR             5
         R              2
         TV-14        733
         TV-G          94
         TV-MA       1145
         TV-PG        323
         TV-Y         176
         TV-Y7        195
         TV-Y7-FV       1
dtype: int64

#### **Q36.** How do you fill all missing (NaN) values in the 'director' column with the string 'Unknown'?

In [37]:
df['director'] = df['director'].fillna('Unknown')
df.director

0       Kirsten Johnson
1               Unknown
2       Julien Leclercq
3               Unknown
4               Unknown
             ...
8802      David Fincher
8803            Unknown
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
Name: director, Length: 8807, dtype: str

#### **Q37.** How do you drop every row from the DataFrame where ANY column contains a missing value?

In [38]:
df.dropna().info()

<class 'pandas.DataFrame'>
Index: 7290 entries, 1 to 8806
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         7290 non-null   str
 1   type            7290 non-null   str
 2   title           7290 non-null   str
 3   director        7290 non-null   str
 4   cast            7290 non-null   str
 5   country         7290 non-null   str
 6   date_added      7290 non-null   str
 7   release_year    7290 non-null   int64
 8   rating          7290 non-null   str
 9   duration        7290 non-null   str
 10  listed_in       7290 non-null   str
 11  description     7290 non-null   str
 12  dataset_source  7290 non-null   str
dtypes: int64(1), str(12)
memory usage: 797.3 KB

#### **Q38.** How do you drop rows only if they contain missing values specifically within the 'cast' or 'director' columns?

In [39]:
df.dropna(subset=['cast','director'])

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Netfilx
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Netfilx
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,Netfilx
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,Netfilx
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netfilx
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netfilx
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx

#### **Q39.** Convert the string values in the 'date_added' column into actual pandas datetime objects.

In [40]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

#### **Q40.** Extract only the year component from the newly converted 'date_added' datetime column and save it into a new column called 'year_added'.

In [41]:
df['year_added']=df['date_added'].dt.year

#### **Q41.** Extract the month name (e.g., January, February) from the 'date_added' column and store it in a column called 'month_added'.

In [42]:
df['month_added']=df['date_added'].dt.month

#### **Q42.** Find the total number of content titles added to Netflix for each specific calendar year using 'date_added'.

In [43]:
df.groupby(df['date_added'].dt.year).size()

date_added
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      10
2014.0      23
2015.0      73
2016.0     418
2017.0    1164
2018.0    1625
2019.0    1999
2020.0    1878
2021.0    1498
dtype: int64

#### **Q43.** Create a new column called 'is_recent' that contains True if the 'release_year' is greater than or equal to 2020, and False otherwise.

In [44]:
import numpy as np
df['is_recent']=np.where(df['release_year']>=2020,True,False)

#### **Q44.** Use the .apply() method with a lambda function to convert all string inputs in the 'title' column to uppercase.

In [45]:
df.title.apply(lambda x:x.upper())

0        DICK JOHNSON IS DEAD
1               BLOOD & WATER
2                   GANGLANDS
3       JAILBIRDS NEW ORLEANS
4                KOTA FACTORY
                ...
8802                   ZODIAC
8803              ZOMBIE DUMB
8804               ZOMBIELAND
8805                     ZOOM
8806                   ZUBAAN
Name: title, Length: 8807, dtype: str

#### **Q45.** Write a custom python function that categorizes 'release_year' into 'Classic' (before 2000), 'Modern' (2000-2015), and 'New' (after 2015), then apply it to the DataFrame.

In [46]:
def category(row):
    if row['release_year']<2000:
        return 'Classic'
    elif row['release_year']>2000 and row['release_year']<=2015:
        return 'Modern'
    else:
        return 'New'
    
df['category']=df.apply(category,axis=1)

#### **Q46.** How do you calculate the cumulative count of titles grouped by 'release_year' over time?

In [47]:
df.groupby('release_year').size().cumsum()

release_year
1925       1
1942       3
1943       6
1944       9
1945      13
        ...
2017    5085
2018    6232
2019    7262
2020    8215
2021    8807
Length: 74, dtype: int64

#### **Q47.** Find the absolute maximum value in the 'duration' column. What problem do you instantly face with string formats like '90 min' vs '2 Seasons'?

In [48]:
df['duration_num'] = pd.to_numeric(
    df['duration'].str.extract(r'(\d+)')[0],
    errors='coerce'
)

df['duration_num'].max()

np.float64(312.0)

#### **Q48.** Create a filtered DataFrame containing only 'Movie' items, and split/extract the numeric digits from the 'duration' column into an integer column named 'duration_minutes'.

In [49]:
Movies = df.loc[df['type']=='Movie'].copy()
Movies['num-duration']=pd.to_numeric(Movies['duration'].str.extract(r'(\d+)')[0],errors='coerce')

#### **Q49.** Create a filtered DataFrame containing only 'TV Show' items, and extract the number of seasons into an integer column named 'season_count'.

In [50]:
show = df.loc[df['type']=='TV Show'].copy()
show['season_count']=pd.to_numeric(show['duration'].str.extract(r'(\d+)')[0],errors='coerce')

#### **Q50.** Find the average 'duration_minutes' for all Netflix Movies after completing the extraction task.

In [51]:
Movies['num-duration'].mean()

np.float64(99.57718668407311)

#### **Q51.** Find the maximum number of seasons a TV show has in this dataset.

In [52]:
show.loc[show['season_count'].max()]['title']

'Falsa identidad'

#### **Q52.** Use string manipulation (.str.contains) to find all movies or TV shows that have the word 'Zodiac' in their title (case-insensitive).

In [53]:
df.loc[df['title'].str.contains('Zodiac')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
2998,s2999,TV Show,​SAINT SEIYA: Knights of the Zodiac,Unknown,"Bryson Baugus, Emily Neves, Blake Shepard, Pat...",Japan,2020-01-23,2020,TV-14,2 Seasons,"Anime Series, International TV Shows",Seiya and the Knights of the Zodiac rise again...,Netfilx,2020.0,1.0,True,New,2.0
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx,2019.0,11.0,False,Modern,158.0

#### **Q53.** Count how many titles contain the word 'Love' or 'love' inside their 'description' column.

In [54]:
df.loc[(df['title'].str.contains('Love')) | (df['description'].str.contains('love'))]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,Netfilx,2021.0,9.0,False,Classic,166.0
25,s26,TV Show,Love on the Spectrum,Unknown,Brooke Satchwell,Australia,2021-09-21,2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...,Netfilx,2021.0,9.0,True,New,2.0
26,s27,Movie,Minsara Kanavu,Rajiv Menon,"Arvind Swamy, Kajol, Prabhu Deva, Nassar, S.P....",NaN,2021-09-21,1997,TV-PG,147 min,"Comedies, International Movies, Music & Musicals",A tangled love triangle ensues when a man fall...,Netfilx,2021.0,9.0,False,Classic,147.0
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,2021-09-20,2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...,Netfilx,2021.0,9.0,False,Modern,103.0
30,s31,Movie,Ankahi Kahaniya,"Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...","Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...",NaN,2021-09-17,2021,TV-14,111 min,"Dramas, Independent Movies, International Movies","As big city life buzzes around them, lonely so...",Netfilx,2021.0,9.0,True,New,111.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8748,s8749,Movie,Winter of Our Dreams,John Duigan,"Judy Davis, Bryan Brown, Cathy Downes, Baz Luh...",Australia,2016-11-01,1981,NR,86 min,"Classic Movies, Dramas","After the death of a long-ago lover, married p...",Netfilx,2016.0,11.0,False,Classic,86.0
8761,s8762,Movie,Wrong No.,Yasir Nawaz,"Javed Sheikh, Danish Taimoor, Janita Asma, Nay...",Pakistan,2017-07-01,2015,TV-14,133 min,"Comedies, International Movies, Romantic Movies",Two identical strangers pursue their respectiv...,Netfilx,2017.0,7.0,False,Modern,133.0
8770,s8771,Movie,Yaadein,Subhash Ghai,"Jackie Shroff, Hrithik Roshan, Kareena Kapoor,...",India,2018-03-01,2001,TV-14,171 min,"Dramas, International Movies, Romantic Movies",Two young lovers set out to overcome the obsta...,Netfilx,2018.0,3.0,False,Modern,171.0
8771,s8772,Movie,Yaara O Dildaara,Ksshitij Chaudhary,"Harbhajan Mann, Tulip Joshi, Kabir Bedi, Gulza...",India,2017-11-01,2011,TV-14,132 min,"Dramas, International Movies, Music & Musicals",The patriarch of a wealthy family with one ind...,Netfilx,2017.0,11.0,False,Modern,132.0
8800,s8801,TV Show,Zindagi Gulzar Hai,Unknown,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre...",Netfilx,2016.0,12.0,False,Modern,1.0

#### **Q54.** Find the top 5 longest movies based on the 'duration_minutes' column you created.

In [55]:
movie = df.loc[df['type']=='Movie'].copy()
movie['duration_minutes']=pd.to_numeric(movie['duration'].str.extract(r'(\d+)')[0],errors='coerce')
movie_sort = movie.sort_values(by='duration_minutes',ascending=False)
movie_sort.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num,duration_minutes
4253,s4254,Movie,Black Mirror: Bandersnatch,Unknown,"Fionn Whitehead, Will Poulter, Craig Parkinson...",United States,2018-12-28,2018,TV-MA,312 min,"Dramas, International Movies, Sci-Fi & Fantasy","In 1984, a young programmer begins to question...",Netfilx,2018.0,12.0,False,New,312.0,312.0
717,s718,Movie,Headspace: Unwind Your Mind,Unknown,"Andy Puddicombe, Evelyn Lewis Prieto, Ginger D...",NaN,2021-06-15,2021,TV-G,273 min,Documentaries,"Do you want to relax, meditate or sleep deeply...",Netfilx,2021.0,6.0,True,New,273.0,273.0
2491,s2492,Movie,The School of Mischief,Houssam El-Din Mustafa,"Suhair El-Babili, Adel Emam, Saeed Saleh, Youn...",Egypt,2020-05-21,1973,TV-14,253 min,"Comedies, Dramas, International Movies",A high school teacher volunteers to transform ...,Netfilx,2020.0,5.0,False,Classic,253.0,253.0
2487,s2488,Movie,No Longer kids,Samir Al Asfory,"Said Saleh, Hassan Moustafa, Ahmed Zaki, Youne...",Egypt,2020-05-21,1979,TV-14,237 min,"Comedies, Dramas, International Movies",Hoping to prevent their father from skipping t...,Netfilx,2020.0,5.0,False,Classic,237.0,237.0
2484,s2485,Movie,Lock Your Girls In,Fouad El-Mohandes,"Fouad El-Mohandes, Sanaa Younes, Sherihan, Ahm...",NaN,2020-05-21,1982,TV-PG,233 min,"Comedies, International Movies, Romantic Movies",A widower believes he must marry off his three...,Netfilx,2020.0,5.0,False,Classic,233.0,233.0

#### **Q55.** Find the top 5 oldest movies/shows available in this dataset.

In [56]:
movie_sort=movie.sort_values(by='release_year',ascending=False)
movie_sort.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num,duration_minutes
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,2017-03-31,1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,Netfilx,2017.0,3.0,False,Classic,61.0,61.0
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,2017-03-31,1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...,Netfilx,2017.0,3.0,False,Classic,82.0,82.0
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,2017-03-31,1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,Netfilx,2017.0,3.0,False,Classic,45.0,45.0
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,2017-03-31,1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,Netfilx,2017.0,3.0,False,Classic,18.0,18.0
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,2017-03-31,1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,Netfilx,2017.0,3.0,False,Classic,52.0,52.0

#### **Q56.** How do you select the 10 rows with the highest values in a numeric column without using the sort_values method?

In [57]:
movie.nlargest(10, 'duration_minutes')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num,duration_minutes
4253,s4254,Movie,Black Mirror: Bandersnatch,Unknown,"Fionn Whitehead, Will Poulter, Craig Parkinson...",United States,2018-12-28,2018,TV-MA,312 min,"Dramas, International Movies, Sci-Fi & Fantasy","In 1984, a young programmer begins to question...",Netfilx,2018.0,12.0,False,New,312.0,312.0
717,s718,Movie,Headspace: Unwind Your Mind,Unknown,"Andy Puddicombe, Evelyn Lewis Prieto, Ginger D...",NaN,2021-06-15,2021,TV-G,273 min,Documentaries,"Do you want to relax, meditate or sleep deeply...",Netfilx,2021.0,6.0,True,New,273.0,273.0
2491,s2492,Movie,The School of Mischief,Houssam El-Din Mustafa,"Suhair El-Babili, Adel Emam, Saeed Saleh, Youn...",Egypt,2020-05-21,1973,TV-14,253 min,"Comedies, Dramas, International Movies",A high school teacher volunteers to transform ...,Netfilx,2020.0,5.0,False,Classic,253.0,253.0
2487,s2488,Movie,No Longer kids,Samir Al Asfory,"Said Saleh, Hassan Moustafa, Ahmed Zaki, Youne...",Egypt,2020-05-21,1979,TV-14,237 min,"Comedies, Dramas, International Movies",Hoping to prevent their father from skipping t...,Netfilx,2020.0,5.0,False,Classic,237.0,237.0
2484,s2485,Movie,Lock Your Girls In,Fouad El-Mohandes,"Fouad El-Mohandes, Sanaa Younes, Sherihan, Ahm...",NaN,2020-05-21,1982,TV-PG,233 min,"Comedies, International Movies, Romantic Movies",A widower believes he must marry off his three...,Netfilx,2020.0,5.0,False,Classic,233.0,233.0
2488,s2489,Movie,Raya and Sakina,Hussein Kamal,"Suhair El-Babili, Shadia, Abdel Moneim Madboul...",NaN,2020-05-21,1984,TV-14,230 min,"Comedies, Dramas, International Movies",When robberies and murders targeting women swe...,Netfilx,2020.0,5.0,False,Classic,230.0,230.0
166,s167,Movie,Once Upon a Time in America,Sergio Leone,"Robert De Niro, James Woods, Elizabeth McGover...","Italy, United States",2021-09-01,1984,R,229 min,"Classic Movies, Dramas",Director Sergio Leone's sprawling crime epic f...,Netfilx,2021.0,9.0,False,Classic,229.0,229.0
7932,s7933,Movie,Sangam,Raj Kapoor,"Raj Kapoor, Vyjayanthimala, Rajendra Kumar, La...",India,2019-12-31,1964,TV-14,228 min,"Classic Movies, Dramas, International Movies",Returning home from war after being assumed de...,Netfilx,2019.0,12.0,False,Classic,228.0,228.0
1019,s1020,Movie,Lagaan,Ashutosh Gowariker,"Aamir Khan, Gracy Singh, Rachel Shelley, Paul ...","India, United Kingdom",2021-04-17,2001,PG,224 min,"Dramas, International Movies, Music & Musicals","In 1890s India, an arrogant British commander ...",Netfilx,2021.0,4.0,False,Modern,224.0,224.0
4573,s4574,Movie,Jodhaa Akbar,Ashutosh Gowariker,"Hrithik Roshan, Aishwarya Rai Bachchan, Sonu S...",India,2018-10-01,2008,TV-14,214 min,"Action & Adventure, Dramas, International Movies","In 16th-century India, what begins as a strate...",Netfilx,2018.0,10.0,False,Modern,214.0,214.0

#### **Q57.** How do you sample exactly 100 random rows from this dataset for prototyping purposes?

In [58]:
df.sample(100)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
2681,s2682,Movie,Stunt School,Ali Yorgancıoğlu,"Aslı İnandık, Toygan Avanoğlu, Tuna Orhan, Can...",Turkey,2020-04-16,2019,TV-G,95 min,"Children & Family Movies, Comedies, Internatio...",An aspiring actress is admitted to a prestigio...,Netfilx,2020.0,4.0,False,New,95.0
3022,s3023,Movie,Bulbul Can Sing,Rima Das,"Arnali Das, Manoranjan Das, Banita Thakuriya, ...",India,2020-01-15,2018,TV-14,95 min,"Dramas, Independent Movies, International Movies",Exploring their sexual identities in the face ...,Netfilx,2020.0,1.0,False,New,95.0
6521,s6522,Movie,Command and Control,Robert Kenner,NaN,United States,2017-05-15,2017,TV-PG,92 min,Documentaries,"Chronicling a 1980 Titan II missile accident, ...",Netfilx,2017.0,5.0,False,New,92.0
4883,s4884,Movie,Si saben cómo me pongo ¿pá qué me invitan?,Fernando Ayllón,"Ricardo Quevedo, Iván Marín, Freddy Beltrán, N...",Colombia,2018-05-03,2018,TV-MA,89 min,"Comedies, International Movies",When four unhappy couples attend a spiritual r...,Netfilx,2018.0,5.0,False,New,89.0
6983,s6984,Movie,Holding the Man,Neil Armfield,"Ryan Corr, Craig Stott, Kerry Fox, Camilla Ah ...",Australia,2016-08-01,2015,TV-MA,128 min,"Dramas, International Movies, LGBTQ Movies","In 1970s Australia, two teen boys fall in love...",Netfilx,2016.0,8.0,False,Modern,128.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2560,s2561,Movie,"Sí, Mi Amor",Pedro Flores Maldonado,"Yiddá Eslava, Julián Zucchi, Andrés Salas, Mag...",NaN,2020-05-06,2020,TV-MA,107 min,"Comedies, International Movies, Romantic Movies",A blindsided boyfriend must prove his fidelity...,Netfilx,2020.0,5.0,True,New,107.0
4555,s4556,Movie,The Meaning of Monty Python,Albert Sharpe,NaN,United Kingdom,2018-10-02,2013,TV-MA,60 min,Documentaries,Five Pythons reflect on their creative process...,Netfilx,2018.0,10.0,False,Modern,60.0
6601,s6602,TV Show,Devlok with Devdutt Pattanaik,Unknown,"Rasika Dugal, Devdutt Pattanaik",India,2018-10-15,2017,TV-PG,1 Season,International TV Shows,"Through chats with host Rasika Dugal, mytholog...",Netfilx,2018.0,10.0,False,New,1.0
3832,s3833,Movie,Dry Martina,Che Sandoval,"Antonella Costa, Patricio Contreras, Geraldine...","Chile, Argentina",2019-05-11,2018,TV-MA,100 min,"Dramas, Independent Movies, International Movies",An odd encounter with a fan and a tryst with t...,Netfilx,2019.0,5.0,False,New,100.0
3933,s3934,Movie,Petta (Telugu Version),Karthik Subbaraj,"Rajnikanth, Vijay Sethupathi, M. Sasikumar, Na...",NaN,2019-04-07,2019,TV-14,170 min,"Action & Adventure, Comedies, Dramas","An affable, newly appointed college warden pro...",Netfilx,2019.0,4.0,False,New,170.0

#### **Q58.** How do you sample 10% of the entire dataset randomly, establishing a random seed state of 42 for reproducibility?

In [59]:
df.sample(frac=0.10, random_state=42)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
4970,s4971,Movie,"Game Over, Man!",Kyle Newacheck,"Adam DeVine, Anders Holm, Blake Anderson, Utka...",United States,2018-03-23,2018,TV-MA,102 min,"Action & Adventure, Comedies",Three buddies with big dreams go from underach...,Netfilx,2018.0,3.0,False,New,102.0
3362,s3363,Movie,Arsenio Hall: Smart & Classy,Brian Volk-Weiss,Arsenio Hall,United States,2019-10-29,2019,TV-MA,63 min,Stand-Up Comedy,"In his first stand-up special, Arsenio Hall di...",Netfilx,2019.0,10.0,False,New,63.0
5494,s5495,TV Show,Kazoops!,Unknown,"Reece Pockney, Scott Langley, Alex Babic, Gemm...",Australia,2017-05-05,2017,TV-Y,3 Seasons,Kids' TV,Music meets imagination in this inventive anim...,Netfilx,2017.0,5.0,False,New,3.0
1688,s1689,TV Show,We Are the Champions,Unknown,NaN,United States,2020-11-17,2020,TV-MA,1 Season,"Docuseries, Reality TV","Explore an array of unique competitions, from ...",Netfilx,2020.0,11.0,True,New,1.0
1349,s1350,TV Show,"Pablo Escobar, el patrón del mal",Unknown,"Andrés Parra, Angie Cepeda, Cecilia Navia, Vic...",Colombia,2021-02-03,2012,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",From his days as a petty thief to becoming hea...,Netfilx,2021.0,2.0,False,Modern,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,s350,Movie,Seabiscuit,Gary Ross,"Tobey Maguire, Jeff Bridges, Chris Cooper, Eli...",United States,2021-08-01,2003,PG-13,141 min,"Dramas, Sports Movies",An ungainly-looking colt becomes a winning tho...,Netfilx,2021.0,8.0,False,Modern,141.0
7524,s7525,Movie,Mujhse Shaadi Karogi,David Dhawan,"Rajpal Yadav, Amrish Puri, Kader Khan, Shashi ...",India,2019-12-31,2004,TV-PG,158 min,"Comedies, International Movies, Romantic Movies","Samir must overcome a hostile horoscope, a hot...",Netfilx,2019.0,12.0,False,Modern,158.0
7406,s7407,TV Show,Maron,Unknown,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaT,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",Netfilx,NaN,NaN,False,New,4.0
7216,s7217,Movie,KL Zombi,Woo Ming Jin,"Zizan Razak, Siti Saleha, Zain Hamid, Izara Ai...",Malaysia,2017-08-21,2013,TV-14,92 min,"Comedies, Horror Movies, International Movies",A field hockey-playing pizza delivery boy find...,Netfilx,2017.0,8.0,False,Modern,92.0
4141,s4142,TV Show,Littlest Pet Shop: A World of Our Own,Unknown,"Rhona Rees, Ingrid Nilson, Diana Kaarina, Trav...",United States,2019-02-01,2018,TV-Y7,2 Seasons,Kids' TV,"In Paw-Tucket, pets of all types form friendsh...",Netfilx,2019.0,2.0,False,New,2.0

#### **Q59.** Replace all occurrences of 'TV-MA' in the 'rating' column with 'Mature Audiences' using the .replace() mapping method.

In [60]:
df['rating'] = df['rating'].replace({
    'TV-MA': 'Mature Audiences'
})
df.rating

0                  PG-13
1       Mature Audiences
2       Mature Audiences
3       Mature Audiences
4       Mature Audiences
              ...
8802                   R
8803               TV-Y7
8804                   R
8805                  PG
8806               TV-14
Name: rating, Length: 8807, dtype: str

#### **Q60.** How do you change the data type of the 'release_year' column from int64 to float64 or int32 explicitly?

In [61]:

df['release_year'].astype('float64')
df['release_year'].astype('int32')

0       2020
1       2021
2       2021
3       2021
4       2021
        ...
8802    2007
8803    2018
8804    2009
8805    2006
8806    2015
Name: release_year, Length: 8807, dtype: int32

## Phase 3: Advanced Transformations, Aggregations & Text Mining (Q61 - Q80)

#### **Q61.** The 'cast' column contains comma-separated actor names. How do you split this string and explode the rows so each individual actor gets their own separate row?

In [62]:
df1 = df.copy()
df1['cast']= df1['cast'].str.split(', ')
df1_explode = df1.explode('cast')
df1_explode

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx,2021.0,9.0,True,New,90.0
1,s2,TV Show,Blood & Water,Unknown,Ama Qamata,South Africa,2021-09-24,2021,Mature Audiences,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx,2021.0,9.0,True,New,2.0
1,s2,TV Show,Blood & Water,Unknown,Khosi Ngema,South Africa,2021-09-24,2021,Mature Audiences,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx,2021.0,9.0,True,New,2.0
1,s2,TV Show,Blood & Water,Unknown,Gail Mabalane,South Africa,2021-09-24,2021,Mature Audiences,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx,2021.0,9.0,True,New,2.0
1,s2,TV Show,Blood & Water,Unknown,Thabang Molaba,South Africa,2021-09-24,2021,Mature Audiences,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx,2021.0,9.0,True,New,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8806,s8807,Movie,Zubaan,Mozez Singh,Manish Chaudhary,India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx,2019.0,3.0,False,Modern,111.0
8806,s8807,Movie,Zubaan,Mozez Singh,Meghna Malik,India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx,2019.0,3.0,False,Modern,111.0
8806,s8807,Movie,Zubaan,Mozez Singh,Malkeet Rauni,India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx,2019.0,3.0,False,Modern,111.0
8806,s8807,Movie,Zubaan,Mozez Singh,Anita Shabdish,India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx,2019.0,3.0,False,Modern,111.0
8806,s8807,Movie,Zubaan,Mozez Singh,Chittaranjan Tripathy,India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx,2019.0,3.0,False,Modern,111.0

#### **Q62.** After exploding the 'cast' column, find the top 10 most frequently appearing actors across all Netflix titles.

In [63]:
df1_explode['cast'].value_counts().head(10)

cast
Anupam Kher         43
Shah Rukh Khan      35
Julie Tejwani       33
Naseeruddin Shah    32
Takahiro Sakurai    32
Rupa Bhimani        31
Akshay Kumar        30
Om Puri             30
Yuki Kaji           29
Amitabh Bachchan    28
Name: count, dtype: int64

#### **Q63.** The 'listed_in' column contains multiple genres separated by commas. Explode this column and find the top 5 most popular genres on Netflix.

In [64]:
df3 = df.copy()
df3['listed_in']=df3['listed_in'].str.split(', ')
df3_exploded = df3.explode('listed_in')
df3_exploded['listed_in'].value_counts().head(5)

listed_in
International Movies      2752
Dramas                    2427
Comedies                  1674
International TV Shows    1351
Documentaries              869
Name: count, dtype: int64

#### **Q64.** Calculate the percentage distribution of 'Movie' vs 'TV Show' across the entire dataset using value_counts.

In [65]:
df['type'].value_counts(normalize=True)*100

type
Movie      69.615079
TV Show    30.384921
Name: proportion, dtype: float64

#### **Q65.** Create a pivot table showing the count of titles, with 'release_year' as rows and 'type' as columns.

In [66]:
pivot_table = pd.pivot_table(
    df,
    index='release_year',
    columns='type',
    values='title',
    aggfunc='count',
    fill_value=0
)

pivot_table

type          Movie  TV Show
release_year
1925              0        1
1942              2        0
1943              3        0
1944              3        0
1945              3        1
...             ...      ...
2017            767      265
2018            767      380
2019            633      397
2020            517      436
2021            277      315

[74 rows x 2 columns]

#### **Q66.** Filter the pivot table from the previous question to only show release years from 2015 to 2021.

In [67]:
pivot_table.loc[2015:2021]

type          Movie  TV Show
release_year
2015            398      162
2016            658      244
2017            767      265
2018            767      380
2019            633      397
2020            517      436
2021            277      315

#### **Q67.** Create a cross-tabulation (crosstab) between the 'country' and 'rating' columns to see distribution patterns.

In [68]:
pd.crosstab(
    df['country'],
    df['rating']
)

rating,66 min,74 min,84 min,G,Mature Audiences,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
country,,,,,,,,,,,,,,,,,
", France, Algeria",0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
", South Korea",0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
Argentina,0,0,0,0,39,0,2,0,0,1,7,2,3,2,0,0,0
"Argentina, Brazil, France, Poland, Germany, Denmark",0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
"Argentina, Chile",0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
"Venezuela, Colombia",0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
Vietnam,0,0,0,0,3,0,0,0,0,0,3,1,0,0,0,0,0
West Germany,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
Zimbabwe,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

#### **Q68.** Find the top 3 most common countries producing content for each individual content 'type' (Movie vs TV Show) using a grouped nlargest operation.

In [69]:

top_3_countries = (
    df.assign(country=df['country'].str.split(', '))
      .explode('country')
      .groupby(['type', 'country'])
      .size()
      .groupby(level=0)
      .nlargest(3)
)

print(top_3_countries)

type     type     country
Movie    Movie    United States     2751
                  India              962
                  United Kingdom     532
TV Show  TV Show  United States      938
                  United Kingdom     272
                  Japan              199
dtype: int64

#### **Q69.** How do you filter out countries that have contributed fewer than 10 total titles to the entire dataset?

In [70]:
country_counts = (
    df['country']
    .dropna()
    .str.split(', ')
    .explode()
    .value_counts()
)

valid_countries = country_counts[country_counts >= 10].index

filtered_countries = country_counts[country_counts >= 10]

filtered_countries.tail(10)

country
Saudi Arabia    13
Austria         12
Luxembourg      12
Finland         11
Greece          11
Hungary         11
Iceland         11
Bulgaria        10
Qatar           10
Peru            10
Name: count, dtype: int64

#### **Q70.** Use the .agg() method on a GroupBy object to calculate both the minimum, maximum, and median 'release_year' simultaneously per 'rating' group.

In [71]:
df.groupby('rating')['release_year'].agg(['min', 'max', 'median'])

                   min   max  median
rating
66 min            2015  2015  2015.0
74 min            2017  2017  2017.0
84 min            2010  2010  2010.0
G                 1956  2020  2004.0
Mature Audiences  1945  2021  2018.0
NC-17             2013  2018  2014.0
NR                1958  2018  2015.0
PG                1973  2021  2012.0
PG-13             1955  2021  2011.0
R                 1962  2021  2014.0
TV-14             1925  2021  2017.0
TV-G              1954  2021  2018.0
TV-PG             1943  2021  2017.0
TV-Y              1992  2021  2018.0
TV-Y7             1981  2021  2017.0
TV-Y7-FV          2012  2018  2015.0
UR                1974  2016  2008.0

#### **Q71.** Write a complex multi-condition filter using .loc to find titles where 'country' is 'United Kingdom', 'rating' is 'TV-PG', and 'release_year' is greater than 2015.

In [72]:
df.loc[(df['country']=='United Kingdom') & (df['rating']=='TV-PG') & (df['release_year']>2015)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
538,s539,TV Show,The A List,Unknown,"Lisa Ambalavanar, Ellie Duckles, Savannah Bake...",United Kingdom,2021-07-06,2021,TV-PG,2 Seasons,"British TV Shows, International TV Shows, TV D...","Romance, rivalry and radical mystery collide a...",Netfilx,2021.0,7.0,True,New,2.0
1129,s1130,TV Show,Secrets of Great British Castles,Unknown,Dan Jones,United Kingdom,2021-04-01,2016,TV-PG,2 Seasons,"British TV Shows, Docuseries, International TV...",Join historian Dan Jones on a journey back in ...,Netfilx,2021.0,4.0,False,New,2.0
1161,s1162,Movie,Elizabeth and Margaret: Love and Loyalty,Unknown,NaN,United Kingdom,2021-03-26,2020,TV-PG,87 min,Documentaries,This documentary takes an intimate look at the...,Netfilx,2021.0,3.0,True,New,87.0
1603,s1604,TV Show,Alien Worlds,Unknown,NaN,United Kingdom,2020-12-02,2020,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...",Applying the laws of life on Earth to the rest...,Netfilx,2020.0,12.0,True,New,1.0
1628,s1629,TV Show,The Repair Shop,Unknown,NaN,United Kingdom,2020-12-01,2018,TV-PG,1 Season,"British TV Shows, Reality TV",Expert artisans restore timeworn family heirlo...,Netfilx,2020.0,12.0,False,New,1.0
2184,s2185,TV Show,Get Even,Unknown,"Kim Adis, Mia McKenna-Bruce, Bethany Antonia, ...",United Kingdom,2020-07-31,2020,TV-PG,1 Season,"British TV Shows, Crime TV Shows, Internationa...","In a secret act of skillful revenge, four priv...",Netfilx,2020.0,7.0,True,New,1.0
2343,s2344,TV Show,Crazy Delicious,Unknown,"Jayde Adams, Carla Hall, Heston Blumenthal, Ni...",United Kingdom,2020-06-24,2020,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...","In this competition show, daring home chefs te...",Netfilx,2020.0,6.0,True,New,1.0
2514,s2515,TV Show,The Big Flower Fight,Unknown,"Natasia Demetriou, Vic Reeves, Kristen Griffit...",United Kingdom,2020-05-18,2020,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...","Ten pairs of florists, sculptors and garden de...",Netfilx,2020.0,5.0,True,New,1.0
2794,s2795,TV Show,The Letter for the King,Unknown,"Amir Wilson, Ruby Ashbourne Serkis, Thaddea Gr...",United Kingdom,2020-03-20,2020,TV-PG,1 Season,"British TV Shows, International TV Shows, TV A...",A young knight in training contends with ancie...,Netfilx,2020.0,3.0,True,New,1.0
2964,s2965,Movie,Night on Earth: Shot in the Dark,Unknown,Samira Wiley,United Kingdom,2020-02-01,2020,TV-PG,59 min,Movies,This look behind the scenes shows how worldwid...,Netfilx,2020.0,2.0,True,New,59.0
2983,s2984,TV Show,Night on Earth,Unknown,Samira Wiley,United Kingdom,2020-01-29,2020,TV-PG,1 Season,"Docuseries, Science & Nature TV",This nature series’ new technology lifts night...,Netfilx,2020.0,1.0,True,New,1.0
3310,s3311,TV Show,Meet the Adebanjos,Unknown,"Wale Ojo, Yetunde Oduwole, Andrea Aboagye, Dan...",United Kingdom,2019-11-04,2016,TV-PG,3 Seasons,"British TV Shows, International TV Shows, TV C...","In South London, tradition clashes with cultur...",Netfilx,2019.0,11.0,False,New,3.0
3400,s3401,TV Show,Interior Design Masters,Unknown,NaN,United Kingdom,2019-10-18,2019,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...",Aspiring interior designers transform a variet...,Netfilx,2019.0,10.0,False,New,1.0
3709,s3710,Movie,ANIMA,Paul Thomas Anderson,Thom Yorke,United Kingdom,2019-06-27,2019,TV-PG,15 min,"Dramas, Independent Movies, Music & Musicals",In a short musical film directed by Paul Thoma...,Netfilx,2019.0,6.0,False,New,15.0
3820,s3821,Movie,PATRICK (2019),Mandie Fletcher,"Beattie Edmondson, Ed Skrein, Tom Bennett, Jen...",United Kingdom,2019-05-16,2019,TV-PG,94 min,"Children & Family Movies, Comedies","When a schoolteacher inherits an adorable pug,...",Netfilx,2019.0,5.0,False,New,94.0
3864,s3865,TV Show,Flinch,Unknown,"Desiree Burch, Lloyd Griffith, Seann Walsh",United Kingdom,2019-05-03,2019,TV-PG,1 Season,Reality TV,Harrowing and hilarious tests await the brave ...,Netfilx,2019.0,5.0,False,New,1.0
4089,s4090,TV Show,The Big Family Cooking Showdown,Unknown,"Zoe Ball, Nadiya Hussain, Giorgio Locatelli, R...",United Kingdom,2019-02-22,2018,TV-PG,2 Seasons,"British TV Shows, International TV Shows, Real...","In this unscripted series, families passionate...",Netfilx,2019.0,2.0,False,New,2.0
4758,s4759,TV Show,Amazing Interiors,Unknown,NaN,United Kingdom,2018-07-20,2018,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...",Meet eccentric homeowners whose seemingly ordi...,Netfilx,2018.0,7.0,False,New,1.0
5111,s5112,TV Show,Myths & Monsters,Daniel Kontur,Nicholas Day,United Kingdom,2017-12-23,2017,TV-PG,1 Season,"British TV Shows, Docuseries",This documentary series takes us to the mythic...,Netfilx,2017.0,12.0,False,New,1.0
5431,s5432,Movie,The Russian Revolution,Cal Seville,Jonathan Kydd,United Kingdom,2017-06-15,2017,TV-PG,47 min,Documentaries,"Starting in 1881, this film describes how the ...",Netfilx,2017.0,6.0,False,New,47.0
5448,s5449,Movie,Amelia: A Tale of Two Sisters,Edward Cotterill,Rachael Stirling,United Kingdom,2017-06-01,2017,TV-PG,44 min,Documentaries,"Eight decades after her disappearance, Amelia ...",Netfilx,2017.0,6.0,False,New,44.0
5451,s5452,Movie,Jackie: A Tale of Two Sisters,Edward Cotterill,Rachael Stirling,United Kingdom,2017-06-01,2017,TV-PG,44 min,Documentaries,Rachael Stirling narrates this multifaceted po...,Netfilx,2017.0,6.0,False,New,44.0
5466,s5467,Movie,The Mitfords: A Tale of Two Sisters,Edward Cotterill,Rachael Stirling,United Kingdom,2017-06-01,2017,TV-PG,44 min,Documentaries,Jessica and Diana were sisters who were separa...,Netfilx,2017.0,6.0,False,New,44.0
5503,s5504,Movie,JFK: The Making of a President,Edward Cotterill,NaN,United Kingdom,2017-05-01,2017,TV-PG,44 min,Documentaries,Explore how John F. Kennedy's worldview was in...,Netfilx,2017.0,5.0,False,New,44.0
5573,s5574,Movie,Notes on Blindness,"Peter Middleton, James Spinney","Dan Renton Skinner, Simone Kirby",United Kingdom,2017-03-15,2016,TV-PG,87 min,"Documentaries, Dramas, International Movies",Based on the audio diaries of academic and the...,Netfilx,2017.0,3.0,False,New,87.0
5795,s5796,Movie,The White Helmets,Orlando von Einsiedel,NaN,United Kingdom,2016-09-16,2016,TV-PG,41 min,Documentaries,As daily airstrikes pound civilian targets in ...,Netfilx,2016.0,9.0,False,New,41.0
5967,s5968,Movie,'89,Unknown,"Lee Dixon, Ian Wright, Paul Merson",United Kingdom,2018-05-16,2017,TV-PG,87 min,Sports Movies,"Mixing old footage with interviews, this is th...",Netfilx,2018.0,5.0,False,New,87.0
6253,s6254,TV Show,Battlefield Recovery,Unknown,NaN,United Kingdom,2016-08-01,2016,TV-PG,1 Season,"British TV Shows, Docuseries, Reality TV",A four-man team heads to Latvia and Poland to ...,Netfilx,2016.0,8.0,False,New,1.0
6398,s6399,TV Show,Cabins in the Wild with Dick Strawbridge,Unknown,"Dick Strawbridge, William Hardie",United Kingdom,2018-09-15,2017,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...",Engineer Dick Strawbridge and craftsman Will H...,Netfilx,2018.0,9.0,False,New,1.0
6487,s6488,TV Show,City in the Sky,Unknown,NaN,United Kingdom,2017-10-01,2016,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",This series explores the magnitude and scale o...,Netfilx,2017.0,10.0,False,New,1.0
6606,s6607,Movie,Diana: 7 Days That Shook the World,Ben Ryder,James D'Arcy,United Kingdom,2017-07-28,2017,TV-PG,93 min,Documentaries,This illuminating documentary examines the aft...,Netfilx,2017.0,7.0,False,New,93.0
6607,s6608,Movie,Diana: In Her Own Words,Unknown,NaN,United Kingdom,2017-12-01,2017,TV-PG,113 min,"Documentaries, International Movies",Featuring archival footage and personal record...,Netfilx,2017.0,12.0,False,New,113.0
6785,s6786,TV Show,Forces of Nature,Unknown,NaN,United Kingdom,2017-03-01,2016,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",This dynamic series spans the globe to explain...,Netfilx,2017.0,3.0,False,New,1.0
6835,s6836,TV Show,Genius of the Modern World,Unknown,Bettany Hughes,United Kingdom,2017-08-01,2016,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...",Historian Bettany Hughes explores the intellec...,Netfilx,2017.0,8.0,False,New,1.0
6894,s6895,TV Show,Great Interior Design Challenge,Unknown,"Tom Dyckhoff, Daniel Hopwood, Sophie Robinson",United Kingdom,NaT,2016,TV-PG,2 Seasons,"British TV Shows, International TV Shows, Real...","In this reality series, amateur interior desig...",Netfilx,NaN,NaN,False,New,2.0
6895,s6896,TV Show,Great Yellowstone Thaw,Unknown,NaN,United Kingdom,2017-10-01,2017,TV-PG,1 Season,"Docuseries, Science & Nature TV",This series explores the effects of the extrem...,Netfilx,2017.0,10.0,False,New,1.0
6978,s6979,Movie,Hitler's Olympics,Daniel Kontur,NaN,United Kingdom,2016-08-01,2016,TV-PG,44 min,"Documentaries, Sports Movies","Hitler, Nazi propaganda and 1936 Berlin Olympi...",Netfilx,2016.0,8.0,False,New,44.0
7076,s7077,Movie,Influx,Luca Vullo,NaN,United Kingdom,2018-04-01,2016,TV-PG,90 min,"Documentaries, International Movies",Italians in London reveal the ups and downs of...,Netfilx,2018.0,4.0,False,New,90.0
7538,s7539,TV Show,My Hotter Half,Unknown,Melvin Odoom,United Kingdom,2019-07-22,2017,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...",Couples compete to see who can take the sexies...,Netfilx,2019.0,7.0,False,New,1.0
7573,s7574,TV Show,Nature's Great Race,Unknown,Liz Bonnin,United Kingdom,2017-10-01,2016,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",Epic footage captures three of the world's mos...,Netfilx,2017.0,10.0,False,New,1.0
7846,s7847,Movie,Red Trees,Marina Willer,Tim Piggott-Smith,United Kingdom,2018-03-24,2017,TV-PG,80 min,"Documentaries, International Movies",A documentarian details her Jewish family's es...,Netfilx,2018.0,3.0,False,New,80.0
7864,s7865,TV Show,Revolting Rhymes,"Jani Lachauer, Jakob Schuh","Rob Brydon, Bertie Carvel, Gemma Chan, Dominic...",United Kingdom,2018-02-01,2017,TV-PG,1 Season,"British TV Shows, Kids' TV",Popular fairy tales take on a darkly comic edg...,Netfilx,2018.0,2.0,False,New,1.0
8129,s8130,TV Show,SuperNature: Wild Flyers,Unknown,NaN,United Kingdom,2017-03-01,2016,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",This series examines the aerodynamics of fligh...,Netfilx,2017.0,3.0,False,New,1.0
8331,s8332,TV Show,The Great British Baking Show: Masterclass,Unknown,"Mary Berry, Paul Hollywood",United Kingdom,2018-12-01,2018,TV-PG,4 Seasons,"British TV Shows, Reality TV",Hosts Mary Berry and Paul Hollywood leave the ...,Netfilx,2018.0,12.0,False,New,4.0
8565,s8566,Movie,The World's Most Wanted Animal,Victoria Bromley,Maria Diekmann,United Kingdom,2019-04-01,2018,TV-PG,53 min,Documentaries,A conservationist shares her emotional journey...,Netfilx,2019.0,4.0,False,New,53.0
8692,s8693,Movie,Walk with Me,"Marc Francis, Max Pugh","Benedict Cumberbatch, Thich Nhat Hanh",United Kingdom,2017-12-26,2017,TV-PG,94 min,Documentaries,A community of monks in France led by Zen Budd...,Netfilx,2017.0,12.0,False,New,94.0
8712,s8713,TV Show,Weird Wonders of the World,Unknown,Chris Packham,United Kingdom,NaT,2016,TV-PG,2 Seasons,"British TV Shows, Docuseries, Science & Nature TV",From animal oddities and bizarre science to me...,Netfilx,NaN,NaN,False,New,2.0
8758,s8759,TV Show,World's Busiest Cities,Unknown,"Anita Rani, Ade Adepitan, Dan Snow",United Kingdom,2019-02-01,2017,TV-PG,1 Season,"British TV Shows, Docuseries","From Moscow to Mexico City, three BBC journali...",Netfilx,2019.0,2.0,False,New,1.0

#### **Q72.** Find the director who has directed the highest number of 'Movies' in the dataset (exclude missing values).

In [73]:
director_counts = df.loc[(df['type'] == 'Movie') & (df['director'] != 'Unknown'),'director'].value_counts()

director_counts.head(1)

director
Rajiv Chilaka    19
Name: count, dtype: int64

#### **Q73.** Identify rows where the 'date_added' year is different from the 'release_year' and calculate what percentage of the dataset this represents.

In [74]:
differ = df.loc[df['date_added'].dt.year != df['release_year']]
percentage = (differ.shape[0]/df.shape[0])*100
print(percentage)

63.41546497104575

#### **Q74.** How do you look up the specific title 'Zombieland' using boolean indexing and extract its exact 'duration' value as a scalar string?

In [75]:
df.loc[df['title']=='Zombieland','duration'].iloc[0]

'88 min'

#### **Q75.** Write a query using the .query() method syntax to filter for Movies released in the United States after 2018.

In [76]:
df.query("country == 'United Kingdom' and release_year > 2018")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,Netfilx,2021.0,9.0,True,New,9.0
32,s33,TV Show,Sex Education,Unknown,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,2021-09-17,2020,Mature Audiences,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...,Netfilx,2021.0,9.0,True,New,3.0
65,s66,TV Show,Numberblocks,Unknown,"Beth Chalmers, David Holt, Marcel McCalla, Ter...",United Kingdom,2021-09-15,2021,TV-Y,6 Seasons,Kids' TV,"In a place called Numberland, math adds up to ...",Netfilx,2021.0,9.0,True,New,6.0
72,s73,TV Show,Jack Whitehall: Travels with My Father,Unknown,"Jack Whitehall, Michael Whitehall",United Kingdom,2021-09-14,2021,Mature Audiences,5 Seasons,"British TV Shows, Docuseries, International TV...",Jovial comic Jack Whitehall invites his stuffy...,Netfilx,2021.0,9.0,True,New,5.0
98,s99,TV Show,Octonauts: Above & Beyond,Unknown,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,2021-09-07,2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...,Netfilx,2021.0,9.0,True,New,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6779,s6780,Movie,For Love or Money,Mark Murphy,"Robert Kazinsky, Samantha Barks, Ed Speleers, ...",United Kingdom,2019-08-16,2019,Mature Audiences,95 min,Comedies,When a goofy but likable millionaire discovers...,Netfilx,2019.0,8.0,False,New,95.0
7658,s7659,Movie,Once Upon a Time in London,Simon Rumley,"Leo Gregory, Terry Stone, Doug Allen, Andy Bec...",United Kingdom,2020-04-15,2019,Mature Audiences,111 min,"Dramas, International Movies","Organized crime came to London in the 1930s, u...",Netfilx,2020.0,4.0,False,New,111.0
7683,s7684,Movie,Our Godfather,"Mark Franchetti, Andrew Meier",Tommaso Buscetta,United Kingdom,2019-09-10,2019,Mature Audiences,93 min,"Documentaries, International Movies","In 1986, Tommaso Buscetta became the first top...",Netfilx,2019.0,9.0,False,New,93.0
8066,s8067,Movie,Speed Is My Need,Mark Sloper,NaN,United Kingdom,2020-01-09,2019,TV-14,75 min,"Documentaries, Sports Movies",This daredevil documentary trails behind and i...,Netfilx,2020.0,1.0,False,New,75.0
8516,s8517,Movie,The Spy Who Fell to Earth,Thomas Meadmore,NaN,United Kingdom,2019-04-05,2019,Mature Audiences,94 min,"Documentaries, International Movies","Based on Dr. Ahron Bregman's book, this docume...",Netfilx,2019.0,4.0,False,New,94.0

#### **Q76.** How do you combine the 'title' and 'type' columns into a single string column formatted as: "Title [Type]"?

In [77]:
df['combined'] = df['title'] + ' [' + df['type'] + ']'
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,dataset_source,year_added,month_added,is_recent,category,duration_num,combined
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Netfilx,2021.0,9.0,True,New,90.0,Dick Johnson Is Dead [Movie]
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,Mature Audiences,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Netfilx,2021.0,9.0,True,New,2.0,Blood & Water [TV Show]
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,Mature Audiences,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Netfilx,2021.0,9.0,True,New,1.0,Ganglands [TV Show]
3,s4,TV Show,Jailbirds New Orleans,Unknown,NaN,NaN,2021-09-24,2021,Mature Audiences,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Netfilx,2021.0,9.0,True,New,1.0,Jailbirds New Orleans [TV Show]
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,Mature Audiences,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Netfilx,2021.0,9.0,True,New,2.0,Kota Factory [TV Show]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Netfilx,2019.0,11.0,False,Modern,158.0,Zodiac [Movie]
8803,s8804,TV Show,Zombie Dumb,Unknown,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Netfilx,2019.0,7.0,False,New,2.0,Zombie Dumb [TV Show]
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Netfilx,2019.0,11.0,False,Modern,88.0,Zombieland [Movie]
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Netfilx,2020.0,1.0,False,Modern,88.0,Zoom [Movie]
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Netfilx,2019.0,3.0,False,Modern,111.0,Zubaan [Movie]

#### **Q77.** Compute a rolling count of titles added per month over time after sorting the DataFrame by a proper datetime index.

In [78]:
df['date_added'] = pd.to_datetime(df['date_added'])

monthly_titles = (
    df.sort_values('date_added')
      .set_index('date_added')
      .resample('ME')
      .size()
)

rolling_count = monthly_titles.rolling(window=3).sum()

rolling_count

date_added
2008-01-31      NaN
2008-02-29      NaN
2008-03-31      2.0
2008-04-30      1.0
2008-05-31      0.0
              ...
2021-05-31    432.0
2021-06-30    527.0
2021-07-31    596.0
2021-08-31    642.0
2021-09-30    618.0
Length: 165, dtype: float64

#### **Q78.** Use the .where() method to replace titles released before 2000 with the value '20th Century Title' while keeping newer titles intact.

In [79]:
df['year_category'] = np.where(
    df['release_year'] < 2000,
    '20th century title',
    '21st century title'
)

#### **Q79.** How do you compute the correlation matrix between numeric columns in pandas? What happens if you run it on this specific dataset?

In [80]:
numeric_df = df.select_dtypes(include='number')
numeric_df.corr()

              release_year  year_added  month_added  duration_num
release_year      1.000000    0.110473    -0.039316     -0.249182
year_added        0.110473    1.000000    -0.160555      0.016436
month_added      -0.039316   -0.160555     1.000000     -0.016876
duration_num     -0.249182    0.016436    -0.016876      1.000000

#### **Q80.** Convert the 'type' and 'rating' columns into categorical data types (pd.Categorical). Explain how this optimizes memory allocation.

In [81]:
df['type'] = pd.Categorical(df['type'])
df['rating'] = pd.Categorical(df['rating'])

#### **Q81.** Write a code snippet to display the memory usage of each individual column in bytes.

In [111]:
df.memory_usage()

Index               132
show_id           70456
type               8823
title             70456
director          70456
cast              70456
country           70456
date_added        70456
release_year      70456
rating             8943
duration          70456
listed_in         70456
description       70456
dataset_source    70456
year_added        70456
month_added       70456
is_recent          8807
category          70456
duration_num      70456
combined          70456
year_category     70456
dtype: int64

#### **Q82.** Find the row index containing the maximum value of 'release_year' using an argmax-equivalent pandas method.

In [113]:
max_idx =df['release_year'].idxmax()

print("Index:", max_idx)
print(df.loc[max_idx])

Index: 1
show_id                                                          s2
type                                                        TV Show
title                                                 Blood & Water
director                                                    Unknown
cast              Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
country                                                South Africa
date_added                                      2021-09-24 00:00:00
release_year                                                   2021
rating                                             Mature Audiences
duration                                                  2 Seasons
listed_in           International TV Shows, TV Dramas, TV Mysteries
description       After crossing paths at a party, a Cape Town t...
dataset_source                                              Netfilx
year_added                                                   2021.0
month_added                                                     9.0
is_recent                                                      True
category                                                        New
duration_num                                                    2.0
combined                                    Blood & Water [TV Show]
year_category                                    21st century title
Name: 1, dtype: object

#### **Q83.** Drop all duplicate rows based strictly on a subset of columns: 'type', 'title', and 'release_year', keeping only the first occurrence.

#### **Q84.** How do you map a dictionary of country-to-continent pairings onto the 'country' column to create a new column 'continent'?

In [85]:
# Your solution code here

#### **Q85.** Write a list comprehension combined with pandas indexing to find all columns that have more than 20% missing values.

In [86]:
# Your solution code here

#### **Q86.** Find the titles where the 'description' length (in characters) is shorter than 50 characters.

In [87]:
# Your solution code here

#### **Q87.** Find the top 3 directors who have worked with the highest number of unique actors.

In [88]:
# Your solution code here

#### **Q88.** What is the difference between df['rating'].unique() and df['rating'].nunique()? Demonstrate both on the dataset.

In [89]:
# Your solution code here

#### **Q89.** Use the .transform() method with groupby to create a column 'total_country_titles' that contains the total title count of the row's country.

In [90]:
# Your solution code here

## Phase 4: Pro-Level Optimization, Multi-indexing & Production Pipelines (Q81 - Q100)

#### **Q90.** The 'country' column often lists multiple countries separated by commas (e.g., 'United States, India, South Korea'). Write an optimized workflow to flatten this column, clean whitespace, and count the definitive global top 10 contributing countries.

In [91]:
# Your solution code here

#### **Q91.** Implement a memory-saving pipeline function that takes the raw dataframe path, drops 'description', fills missing categorical text, downcasts integers, converts objects to categories, and returns the optimized DataFrame.

In [92]:
# Your solution code here

#### **Q92.** Create a multi-index DataFrame by grouping by ['country', 'type', 'rating'] and computing counts. Show how to unstack the 'type' level into columns.

In [93]:
# Your solution code here

#### **Q93.** Using the multi-index DataFrame from the previous question, demonstrate how to select data specifically for 'United States' at the outer index level using the .xs() cross-section tool.

In [94]:
# Your solution code here

#### **Q94.** Calculate the year-over-year growth rate in the number of movies added to Netflix from 2010 to 2021.

In [95]:
# Your solution code here

#### **Q95.** Use pandas string vectorization to parse out the primary/first actor listed in the 'cast' column without using explicit loops or apply functions.

In [96]:
# Your solution code here

#### **Q96.** For each director, find their most frequent content rating category using a lambda custom function inside a groupby expression.

In [97]:
# Your solution code here

#### **Q97.** Write a high-performance query using string-matching regular expressions to find titles whose descriptions start with a number or contain specific special characters.

In [98]:
# Your solution code here

#### **Q98.** Convert the DataFrame into a JSON string structured as an array of nested records, then reconstruct it back into a pandas DataFrame.

In [99]:
# Your solution code here

#### **Q99.** Write a snippet showing how you would slice the DataFrame into chunks of 1000 rows each, process them sequentially, and aggregate a final value count of the 'type' column to mimic out-of-core computing.

In [100]:
# Your solution code here

#### **Q100.** Create a custom styling rule using the df.style API to highlight rows with light green if the title is a Movie and has a 'release_year' of 2021.

In [101]:
# Your solution code here

#### **Q101.** Simulate a merge scenario: Create a dummy secondary DataFrame containing 'show_id' and a mock 'imdb_score'. Perform an inner join and a left join between your Netflix DataFrame and this new mock DataFrame.

In [102]:
# Your solution code here

#### **Q102.** Use the pd.concat() function to split the Netflix DataFrame into two halves (first 50% rows and last 50% rows) and then cleanly stitch them back together seamlessly.

In [103]:
# Your solution code here

#### **Q103.** Demonstrate how to write the fully cleaned and transformed Netflix DataFrame out into a compressed parquet file format using pyarrow or fastparquet engines.

In [104]:
# Your solution code here

#### **Q104.** Write an elegant method chaining block that filters for US movies, extracts the runtime, bins the runtime into 3 categories (Short, Medium, Long), groups by the bins, and displays the count—all in one continuous expression.

In [105]:
# Your solution code here

#### **Q105.** Find rows where the 'director' name shares at least one common word with the 'title' string (excluding common stop words like 'The', 'Of', or 'In').

In [106]:
# Your solution code here

#### **Q106.** How do you determine if any column in your dataframe has a high cardinality (defined as unique values making up more than 90% of the row count)?

In [107]:
# Your solution code here

#### **Q107.** Identify the longest individual string length inside the 'description' column across the entire dataset.

In [108]:
# Your solution code here

#### **Q108.** Show how to find the top 5 months of the year that historical data shows Netflix chooses to release the highest volume of original content.

In [109]:
# Your solution code here

#### **Q109.** Write a script that tracks the execution time of a vectorized pandas operation vs an iterative .iterrows() loop over the Netflix dataset to prove why loops are discouraged.

In [110]:
# Your solution code here