# 🐼 Pandas Mastery Challenge Workbook
### 100 Comprehensive Practice Questions (Beginner to Pro)
**Dataset context:** `netflix_titles.csv`

Use this notebook to solve the challenge questions. For each question, an empty code cell has been provided below the prompt for your implementation.

## Phase 1: Beginner Level Foundations (Q1 - Q25)

#### **Q1.** How do you import the pandas library and read the netflix_titles.csv dataset into a DataFrame named 'df'?

In [3]:
import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

#### **Q2.** How do you display the first 5 rows and the last 5 rows of the Netflix DataFrame?

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

#### **Q3.** How can you find the total number of rows and columns in this dataset?

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

#### **Q4.** Write a command to output all the column names of the DataFrame.

In [6]:
display(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

#### **Q5.** How do you inspect the data types of each column alongside non-null counts using a built-in pandas method?

In [8]:
df.columns.dtype
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

#### **Q6.** How can you obtain a summary of basic statistics (mean, min, max, count) for the numeric columns?

In [9]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

#### **Q7.** How do you count the exact number of missing values (NaN) in every single column?

In [10]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

#### **Q8.** Select only the 'title' column from the DataFrame. What are the two different syntaxes to achieve this?

In [13]:
df.title
df['title'].head()

0     Dick Johnson Is Dead
1            Blood & Water
2                Ganglands
3    Jailbirds New Orleans
4             Kota Factory
Name: title, dtype: str

#### **Q9.** Extract a new DataFrame that contains only three specific columns: 'title', 'type', and 'release_year'.

In [14]:
df[['title','type','release_year']]

                      title     type  release_year
0      Dick Johnson Is Dead    Movie          2020
1             Blood & Water  TV Show          2021
2                 Ganglands  TV Show          2021
3     Jailbirds New Orleans  TV Show          2021
4              Kota Factory  TV Show          2021
...                     ...      ...           ...
8802                 Zodiac    Movie          2007
8803            Zombie Dumb  TV Show          2018
8804             Zombieland    Movie          2009
8805                   Zoom    Movie          2006
8806                 Zubaan    Movie          2015

[8807 rows x 3 columns]

#### **Q10.** How do you filter the DataFrame to show only rows where the 'type' is equal to 'Movie'?

In [15]:
df.loc[df['type']=='Movie']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### **Q11.** How do you filter the rows to show only 'TV Show' entries?

In [16]:
df.loc[df['type']=='TV Show']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

#### **Q12.** Find the total count of unique values in the 'type' column to see how many distinct categories exist.

In [21]:
df['type'].nunique()
df.type.unique

<bound method Series.unique of 0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: str>

#### **Q13.** List all unique values present in the 'rating' column.

In [24]:
list(df.rating.unique())
df.rating.unique().tolist()

['PG-13',
 'TV-MA',
 'PG',
 'TV-14',
 'TV-PG',
 'TV-Y',
 'TV-Y7',
 'R',
 'TV-G',
 'G',
 'NC-17',
 '74 min',
 '84 min',
 '66 min',
 'NR',
 nan,
 'TV-Y7-FV',
 'UR']

#### **Q14.** How do you count how many times each unique 'rating' appears in the dataset?

In [27]:
df.rating.value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

#### **Q15.** Find the frequency count of each unique value in the 'release_year' column.

In [28]:
df['release_year'].value_counts()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1959       1
1925       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

#### **Q16.** How do you select the row at index position 10 using integer-based indexing (.iloc)?

In [29]:
df.iloc[10]

show_id                                                       s11
type                                                      TV Show
title                         Vendetta: Truth, Lies and The Mafia
director                                                      NaN
cast                                                          NaN
country                                                       NaN
date_added                                     September 24, 2021
release_year                                                 2021
rating                                                      TV-MA
duration                                                 1 Season
listed_in       Crime TV Shows, Docuseries, International TV S...
description     Sicily boasts a bold "Anti-Mafia" coalition. B...
Name: 10, dtype: object

#### **Q17.** How do you select rows from index 10 to 20 (inclusive) and columns from 'show_id' to 'director' using label-based indexing (.loc)?

In [30]:
df.loc[10:20,'show_id':'director']

,show_id,type,title,director
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri
12,s13,Movie,Je Suis Karl,Christian Schwochow
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti
14,s15,TV Show,Crime Stories: India Detectives,NaN
15,s16,TV Show,Dear White People,NaN
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams"
17,s18,TV Show,Falsa identidad,NaN
18,s19,Movie,Intrusion,Adam Salky
19,s20,TV Show,Jaguar,NaN
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton

#### **Q18.** How can you check if the 'show_id' column contains any duplicate values?

In [32]:
df.show_id.duplicated().sum()

np.int64(0)

#### **Q19.** Rename the column 'listed_in' to 'genre' and 'cast' to 'actors' in place.

In [33]:
df.rename(columns={'listed_in': 'genre', 'cast': 'actors'})

,show_id,type,title,director,actors,country,date_added,release_year,rating,duration,genre,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### **Q20.** Sort the entire DataFrame by the 'release_year' column in ascending order.

In [36]:
df.sort_values(by='release_year',ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
781,s782,Movie,Black Holes | The Edge of All We Know,Peter Galison,NaN,NaN,"June 2, 2021",2021,TV-14,99 min,Documentaries,Follow scientists on their quest to understand...
762,s763,Movie,Sweet & Sour,Lee Kae-byeok,"Jang Ki-yong, Chae Soo-bin, Jung Soo-jung",South Korea,"June 4, 2021",2021,TV-14,103 min,"Comedies, International Movies, Romantic Movies",Faced with real-world opportunities and challe...
763,s764,TV Show,Sweet Tooth,NaN,"Nonso Anozie, Christian Convery, Adeel Akhtar,...",United States,"June 4, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",On a perilous adventure across a post-apocalyp...
764,s765,Movie,Trippin' with the Kandasamys,Jayan Moodley,"Jailoshini Naidoo, Maeshni Naicker, Madhushan ...",South Africa,"June 4, 2021",2021,TV-14,94 min,"Comedies, International Movies, Romantic Movies","To rekindle their marriages, best friends-turn..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

#### **Q21.** Sort the DataFrame by 'release_year' in descending order so that the newest releases appear first.

In [37]:
df.sort_values(by='release_year', ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
781,s782,Movie,Black Holes | The Edge of All We Know,Peter Galison,NaN,NaN,"June 2, 2021",2021,TV-14,99 min,Documentaries,Follow scientists on their quest to understand...
762,s763,Movie,Sweet & Sour,Lee Kae-byeok,"Jang Ki-yong, Chae Soo-bin, Jung Soo-jung",South Korea,"June 4, 2021",2021,TV-14,103 min,"Comedies, International Movies, Romantic Movies",Faced with real-world opportunities and challe...
763,s764,TV Show,Sweet Tooth,NaN,"Nonso Anozie, Christian Convery, Adeel Akhtar,...",United States,"June 4, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",On a perilous adventure across a post-apocalyp...
764,s765,Movie,Trippin' with the Kandasamys,Jayan Moodley,"Jailoshini Naidoo, Maeshni Naicker, Madhushan ...",South Africa,"June 4, 2021",2021,TV-14,94 min,"Comedies, International Movies, Romantic Movies","To rekindle their marriages, best friends-turn..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

#### **Q22.** How do you reset the index of a DataFrame after sorting it, ensuring the old index is completely dropped?

In [39]:
new_df = df.sort_values(by='release_year').reset_index()
new_df

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
1,7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
2,8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
3,8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
4,8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,862,s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...
8803,861,s862,Movie,Little Singham Future mein Satakli,Prakash Satam,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"May 20, 2021",2021,TV-Y7,47 min,"Children & Family Movies, Comedies",Little Singham and his crew travel to the year...
8804,857,s858,TV Show,The Neighbor,NaN,"Quim Gutiérrez, Clara Lago, Adrián Pino, Catel...",Spain,"May 21, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",Self-centered Javier's life gets a bit messy w...
8805,876,s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
8806,965,s966,TV Show,Yasuke,NaN,"LaKeith Stanfield, Takehiro Hira, Maya Tanida,...",NaN,"April 29, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows",A peaceful boatman once known as the Black Sam...

#### **Q23.** Drop the 'description' column entirely from the DataFrame and return a new DataFrame.

In [47]:
df1 = df.drop(columns='title')
df1

,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8803,s8804,TV Show,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8804,s8805,Movie,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8805,s8806,Movie,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8806,s8807,Movie,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

#### **Q24.** How do you drop both 'director' and 'cast' columns simultaneously within a single line of code?

In [49]:
df2 = df.drop(columns=['director','cast'])

#### **Q25.** Create a new column named 'dataset_source' where every single row contains the static string value 'Netflix'.

In [51]:
df['dataset_source']='Netfilx'
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,dataset_source
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,Netfilx
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",Netfilx
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",Netfilx
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV",Netfilx
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Netfilx
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers",Netfilx
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",Netfilx
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Netfilx
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies",Netfilx
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",Netfilx

## Phase 2: Intermediate Data Wrangling & Analysis (Q26 - Q60)

#### **Q26.** Filter the dataset to find all rows where 'type' is 'Movie' AND the 'release_year' is exactly 2021.

In [ ]:
# Your solution code here

#### **Q27.** Filter the dataset for rows where 'country' is either 'United States' OR 'India'.

In [ ]:
# Your solution code here

#### **Q28.** How do you select rows where the 'country' column value is missing (NaN)?

In [ ]:
# Your solution code here

#### **Q29.** How do you find all rows where the 'director' column is NOT missing (is valid)?

In [ ]:
# Your solution code here

#### **Q30.** Use the .isin() method to filter the DataFrame for rows where the 'rating' is 'PG', 'PG-13', or 'R'.

In [ ]:
# Your solution code here

#### **Q31.** Find all records where the 'release_year' falls strictly between 2018 and 2020 inclusive using a single boundary method.

In [ ]:
# Your solution code here

#### **Q32.** How do you calculate the mean, median, minimum, and maximum values of the 'release_year' column?

In [ ]:
# Your solution code here

#### **Q33.** Group the DataFrame by the 'type' column and calculate the total count of titles within each group.

In [ ]:
# Your solution code here

#### **Q34.** Group by 'rating' and find the average/mean 'release_year' for each rating category.

In [ ]:
# Your solution code here

#### **Q35.** Group the data by both 'type' and 'rating' simultaneously and count the number of rows for each combination.

In [ ]:
# Your solution code here

#### **Q36.** How do you fill all missing (NaN) values in the 'director' column with the string 'Unknown'?

In [ ]:
# Your solution code here

#### **Q37.** How do you drop every row from the DataFrame where ANY column contains a missing value?

In [ ]:
# Your solution code here

#### **Q38.** How do you drop rows only if they contain missing values specifically within the 'cast' or 'director' columns?

In [ ]:
# Your solution code here

#### **Q39.** Convert the string values in the 'date_added' column into actual pandas datetime objects.

In [ ]:
# Your solution code here

#### **Q40.** Extract only the year component from the newly converted 'date_added' datetime column and save it into a new column called 'year_added'.

In [ ]:
# Your solution code here

#### **Q41.** Extract the month name (e.g., January, February) from the 'date_added' column and store it in a column called 'month_added'.

In [ ]:
# Your solution code here

#### **Q42.** Find the total number of content titles added to Netflix for each specific calendar year using 'date_added'.

In [ ]:
# Your solution code here

#### **Q43.** Create a new column called 'is_recent' that contains True if the 'release_year' is greater than or equal to 2020, and False otherwise.

In [ ]:
# Your solution code here

#### **Q44.** Use the .apply() method with a lambda function to convert all string inputs in the 'title' column to uppercase.

In [ ]:
# Your solution code here

#### **Q45.** Write a custom python function that categorizes 'release_year' into 'Classic' (before 2000), 'Modern' (2000-2015), and 'New' (after 2015), then apply it to the DataFrame.

In [ ]:
# Your solution code here

#### **Q46.** How do you calculate the cumulative count of titles grouped by 'release_year' over time?

In [ ]:
# Your solution code here

#### **Q47.** Find the absolute maximum value in the 'duration' column. What problem do you instantly face with string formats like '90 min' vs '2 Seasons'?

In [ ]:
# Your solution code here

#### **Q48.** Create a filtered DataFrame containing only 'Movie' items, and split/extract the numeric digits from the 'duration' column into an integer column named 'duration_minutes'.

In [ ]:
# Your solution code here

#### **Q49.** Create a filtered DataFrame containing only 'TV Show' items, and extract the number of seasons into an integer column named 'season_count'.

In [ ]:
# Your solution code here

#### **Q50.** Find the average 'duration_minutes' for all Netflix Movies after completing the extraction task.

In [ ]:
# Your solution code here

#### **Q51.** Find the maximum number of seasons a TV show has in this dataset.

In [ ]:
# Your solution code here

#### **Q52.** Use string manipulation (.str.contains) to find all movies or TV shows that have the word 'Zodiac' in their title (case-insensitive).

In [ ]:
# Your solution code here

#### **Q53.** Count how many titles contain the word 'Love' or 'love' inside their 'description' column.

In [ ]:
# Your solution code here

#### **Q54.** Find the top 5 longest movies based on the 'duration_minutes' column you created.

In [ ]:
# Your solution code here

#### **Q55.** Find the top 5 oldest movies/shows available in this dataset.

In [ ]:
# Your solution code here

#### **Q56.** How do you select the 10 rows with the highest values in a numeric column without using the sort_values method?

In [ ]:
# Your solution code here

#### **Q57.** How do you sample exactly 100 random rows from this dataset for prototyping purposes?

In [ ]:
# Your solution code here

#### **Q58.** How do you sample 10% of the entire dataset randomly, establishing a random seed state of 42 for reproducibility?

In [ ]:
# Your solution code here

#### **Q59.** Replace all occurrences of 'TV-MA' in the 'rating' column with 'Mature Audiences' using the .replace() mapping method.

In [ ]:
# Your solution code here

#### **Q60.** How do you change the data type of the 'release_year' column from int64 to float64 or int32 explicitly?

In [ ]:
# Your solution code here

## Phase 3: Advanced Transformations, Aggregations & Text Mining (Q61 - Q80)

#### **Q61.** The 'cast' column contains comma-separated actor names. How do you split this string and explode the rows so each individual actor gets their own separate row?

In [ ]:
# Your solution code here

#### **Q62.** After exploding the 'cast' column, find the top 10 most frequently appearing actors across all Netflix titles.

In [ ]:
# Your solution code here

#### **Q63.** The 'listed_in' column contains multiple genres separated by commas. Explode this column and find the top 5 most popular genres on Netflix.

In [ ]:
# Your solution code here

#### **Q64.** Calculate the percentage distribution of 'Movie' vs 'TV Show' across the entire dataset using value_counts.

In [ ]:
# Your solution code here

#### **Q65.** Create a pivot table showing the count of titles, with 'release_year' as rows and 'type' as columns.

In [ ]:
# Your solution code here

#### **Q66.** Filter the pivot table from the previous question to only show release years from 2015 to 2021.

In [ ]:
# Your solution code here

#### **Q67.** Create a cross-tabulation (crosstab) between the 'country' and 'rating' columns to see distribution patterns.

In [ ]:
# Your solution code here

#### **Q68.** Find the top 3 most common countries producing content for each individual content 'type' (Movie vs TV Show) using a grouped nlargest operation.

In [ ]:
# Your solution code here

#### **Q69.** How do you filter out countries that have contributed fewer than 10 total titles to the entire dataset?

In [ ]:
# Your solution code here

#### **Q70.** Use the .agg() method on a GroupBy object to calculate both the minimum, maximum, and median 'release_year' simultaneously per 'rating' group.

In [ ]:
# Your solution code here

#### **Q71.** Write a complex multi-condition filter using .loc to find titles where 'country' is 'United Kingdom', 'rating' is 'TV-PG', and 'release_year' is greater than 2015.

In [ ]:
# Your solution code here

#### **Q72.** Find the director who has directed the highest number of 'Movies' in the dataset (exclude missing values).

In [ ]:
# Your solution code here

#### **Q73.** Identify rows where the 'date_added' year is different from the 'release_year' and calculate what percentage of the dataset this represents.

In [ ]:
# Your solution code here

#### **Q74.** How do you look up the specific title 'Zombieland' using boolean indexing and extract its exact 'duration' value as a scalar string?

In [ ]:
# Your solution code here

#### **Q75.** Write a query using the .query() method syntax to filter for Movies released in the United States after 2018.

In [ ]:
# Your solution code here

#### **Q76.** How do you combine the 'title' and 'type' columns into a single string column formatted as: "Title [Type]"?

In [ ]:
# Your solution code here

#### **Q77.** Compute a rolling count of titles added per month over time after sorting the DataFrame by a proper datetime index.

In [ ]:
# Your solution code here

#### **Q78.** Use the .where() method to replace titles released before 2000 with the value '20th Century Title' while keeping newer titles intact.

In [ ]:
# Your solution code here

#### **Q79.** How do you compute the correlation matrix between numeric columns in pandas? What happens if you run it on this specific dataset?

In [ ]:
# Your solution code here

#### **Q80.** Convert the 'type' and 'rating' columns into categorical data types (pd.Categorical). Explain how this optimizes memory allocation.

In [ ]:
# Your solution code here

#### **Q81.** Write a code snippet to display the memory usage of each individual column in bytes.

In [ ]:
# Your solution code here

#### **Q82.** Find the row index containing the maximum value of 'release_year' using an argmax-equivalent pandas method.

In [ ]:
# Your solution code here

#### **Q83.** Drop all duplicate rows based strictly on a subset of columns: 'type', 'title', and 'release_year', keeping only the first occurrence.

In [ ]:
# Your solution code here

#### **Q84.** How do you map a dictionary of country-to-continent pairings onto the 'country' column to create a new column 'continent'?

In [ ]:
# Your solution code here

#### **Q85.** Write a list comprehension combined with pandas indexing to find all columns that have more than 20% missing values.

In [ ]:
# Your solution code here

#### **Q86.** Find the titles where the 'description' length (in characters) is shorter than 50 characters.

In [ ]:
# Your solution code here

#### **Q87.** Find the top 3 directors who have worked with the highest number of unique actors.

In [ ]:
# Your solution code here

#### **Q88.** What is the difference between df['rating'].unique() and df['rating'].nunique()? Demonstrate both on the dataset.

In [ ]:
# Your solution code here

#### **Q89.** Use the .transform() method with groupby to create a column 'total_country_titles' that contains the total title count of the row's country.

In [ ]:
# Your solution code here

## Phase 4: Pro-Level Optimization, Multi-indexing & Production Pipelines (Q81 - Q100)

#### **Q90.** The 'country' column often lists multiple countries separated by commas (e.g., 'United States, India, South Korea'). Write an optimized workflow to flatten this column, clean whitespace, and count the definitive global top 10 contributing countries.

In [ ]:
# Your solution code here

#### **Q91.** Implement a memory-saving pipeline function that takes the raw dataframe path, drops 'description', fills missing categorical text, downcasts integers, converts objects to categories, and returns the optimized DataFrame.

In [ ]:
# Your solution code here

#### **Q92.** Create a multi-index DataFrame by grouping by ['country', 'type', 'rating'] and computing counts. Show how to unstack the 'type' level into columns.

In [ ]:
# Your solution code here

#### **Q93.** Using the multi-index DataFrame from the previous question, demonstrate how to select data specifically for 'United States' at the outer index level using the .xs() cross-section tool.

In [ ]:
# Your solution code here

#### **Q94.** Calculate the year-over-year growth rate in the number of movies added to Netflix from 2010 to 2021.

In [ ]:
# Your solution code here

#### **Q95.** Use pandas string vectorization to parse out the primary/first actor listed in the 'cast' column without using explicit loops or apply functions.

In [ ]:
# Your solution code here

#### **Q96.** For each director, find their most frequent content rating category using a lambda custom function inside a groupby expression.

In [ ]:
# Your solution code here

#### **Q97.** Write a high-performance query using string-matching regular expressions to find titles whose descriptions start with a number or contain specific special characters.

In [ ]:
# Your solution code here

#### **Q98.** Convert the DataFrame into a JSON string structured as an array of nested records, then reconstruct it back into a pandas DataFrame.

In [ ]:
# Your solution code here

#### **Q99.** Write a snippet showing how you would slice the DataFrame into chunks of 1000 rows each, process them sequentially, and aggregate a final value count of the 'type' column to mimic out-of-core computing.

In [ ]:
# Your solution code here

#### **Q100.** Create a custom styling rule using the df.style API to highlight rows with light green if the title is a Movie and has a 'release_year' of 2021.

In [ ]:
# Your solution code here

#### **Q101.** Simulate a merge scenario: Create a dummy secondary DataFrame containing 'show_id' and a mock 'imdb_score'. Perform an inner join and a left join between your Netflix DataFrame and this new mock DataFrame.

In [ ]:
# Your solution code here

#### **Q102.** Use the pd.concat() function to split the Netflix DataFrame into two halves (first 50% rows and last 50% rows) and then cleanly stitch them back together seamlessly.

In [ ]:
# Your solution code here

#### **Q103.** Demonstrate how to write the fully cleaned and transformed Netflix DataFrame out into a compressed parquet file format using pyarrow or fastparquet engines.

In [ ]:
# Your solution code here

#### **Q104.** Write an elegant method chaining block that filters for US movies, extracts the runtime, bins the runtime into 3 categories (Short, Medium, Long), groups by the bins, and displays the count—all in one continuous expression.

In [ ]:
# Your solution code here

#### **Q105.** Find rows where the 'director' name shares at least one common word with the 'title' string (excluding common stop words like 'The', 'Of', or 'In').

In [ ]:
# Your solution code here

#### **Q106.** How do you determine if any column in your dataframe has a high cardinality (defined as unique values making up more than 90% of the row count)?

In [ ]:
# Your solution code here

#### **Q107.** Identify the longest individual string length inside the 'description' column across the entire dataset.

In [ ]:
# Your solution code here

#### **Q108.** Show how to find the top 5 months of the year that historical data shows Netflix chooses to release the highest volume of original content.

In [ ]:
# Your solution code here

#### **Q109.** Write a script that tracks the execution time of a vectorized pandas operation vs an iterative .iterrows() loop over the Netflix dataset to prove why loops are discouraged.

In [ ]:
# Your solution code here